#SPDX-License-Identifier: MIT-0
---
- name: Add Plex GPG key
  ansible.builtin.apt_key:
    url: "{{ plex_apt_key_url }}"
    state: present

- name: Add Plex APT repository
  ansible.builtin.apt_repository:
    repo: "{{ plex_repo }}"
    state: present
    filename: plex

- name: Download Plex GPG key
  ansible.builtin.get_url:
    url: "{{ plex_apt_key_url }}"
    dest: /usr/share/keyrings/plex.gpg
    mode: '0644'

- name: Add Plex APT repository
  ansible.builtin.apt_repository:
    repo: "{{ plex_repo }}"
    filename: plexmediaserver
    state: present

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Plex Media Server
  ansible.builtin.apt:
    name: plexmediaserver
    state: present

- name: Ensure Plex Media Server is enabled
  ansible.builtin.service:
    name: "{{ plex_service_name }}"
    enabled: true